parameters:
    ac_web_services.default_format_headers:
        json:
            'Content-Type': 'application/json'
        jsonp:
            'Content-Type': 'application/javascript'
        yml:
            'Content-Type': 'application/yaml'
        xml:
            'Content-Type': 'application/xml'
        html:
            'Content-Type': 'text/html; charset=UTF-8'
        xhtml:
            'Content-Type': 'application/xhtml+xml'

services:

    # responsible for instantiating the API request listeners for matching paths
    ac_web_services.kernel_listeners:
        class:        AC\WebServicesBundle\EventListener\WebServiceSubscriber
        arguments:    [@service_container, %ac_web_services.response_format_headers%, %ac_web_services.path_config%]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelEarlyRequest, priority: 255 }
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelLateRequest, priority: -255 }
