parameters:
    ac_web_services.default_format_headers:
        json:
            'content-type': 'application/json'
        jsonp:
            'content-type': 'text/javascript'
        yml:
            'content-type': 'application/yaml'
        xml:
            'content-type': 'application/xml'

services:
    # responsible for instantiating the API request listeners for matching paths
    ac_web_services.request_listener:
        class:        AC\WebServicesBundle\EventListener\ApiBootstrapListener
        arguments:    [@service_container]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1024 }
