services:
    # handles API requests that match based on the app configuration
    ac_web_services.kernel_listeners:
        class: AC\WebServicesBundle\EventListener\WebServiceSubscriber
        arguments:
            - @service_container
            - %ac_web_services.response_format_headers%
            - %ac_web_services.path_config%
            - %ac_web_services.serializable_formats%
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelEarlyRequest, priority: 255 }
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelLateRequest, priority: -255 }

    #TODO: consider moving into optional config file
    ac_web_services.initialized_object_constructor:
        class: AC\WebServicesBundle\Serializer\InitializedObjectConstructor
        arguments:
            - @jms_serializer.unserialize_object_constructor

    jms_serializer.unserialize_object_constructor:
        class: JMS\Serializer\Construction\UnserializeObjectConstructor

    jms_serializer.object_constructor:
        alias: ac_web_services.initialized_object_constructor
        # alias: ac_web_services.initialized_object_constructor public: false

    #TODO: consider moving into optional config file
    ac_web_services.negotiator:
        class: AC\WebServicesBundle\Negotiator
        arguments:
            - %ac_web_services.negotiation.input_format_types%
            - %ac_web_services.negotiation.response_format_priorities%
            - %ac_web_services.negotiation.response_language_priorities%
            - %ac_web_services.negotiation.response_charset_priorities%
