services:
    ac_web_services.form_deserialization_visitor:
        class: AC\WebServicesBundle\Serializer\FormDeserializationVisitor
        arguments: [@jms_serializer.naming_strategy, @jms_serializer.object_constructor]
        tags:
            - { name: jms_serializer.deserialization_visitor, format: form }
