services:
    # responsible for instantiating the API request listeners for matching paths
    ac.webservices.request_listener:
        class:        AC\WebServicesBundle\EventListener\ApiBootstrapListener
        arguments:    [@service_container, %ac_web_services.api_paths%]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1024 }
