services:
    ac_web_services.initialized_object_constructor:
        class: AC\WebServicesBundle\Serializer\InitializedObjectConstructor
        arguments:
            - @ac_web_services.serializer.fallback_object_constructor

    ac_web_services.serializer.fallback_object_constructor:
        class: JMS\Serializer\Construction\UnserializeObjectConstructor

    jms_serializer.object_constructor:
        alias: ac_web_services.initialized_object_constructor
