#generally copied from https://github.com/nelmio/NelmioApiDocBundle/blob/master/.travis.yml

language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer install

script: phpunit
