notifications:
    webhooks: http://ac-dev-bishop.herokuapp.com/bishop/travisci/general
    on_start: true

language: php

php:
    - 5.4
    - 5.5
#    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
#    - SYMFONY_VERSION=dev-master

#matrix:
#    allow_failures:
#		 - hhvm
#        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer install

script: vendor/bin/phpunit
